# Stochastic simulation
death_rate: "0.1 0.1"
birth_rate: "1.0 1.0"
death_interaction: "0.001 0.001"
birth_interaction: "0.0 0.0"
mutation_rate: 1e-3
end_time: 10
starting_population: "1 0"

# Particle model
max_velocity: 6
max_acceleration: 3
friction: 0.8
timestep: 0.005
# end_time: same as for stochastic simulation

# Animation
frame_skip: 99
frame_delay: 17
width: 640
height: 480
